services:
  flaskapp:
    build:
      context: .
      dockerfile: flask/Dockerfile
    volumes:
      - './flask:/app'
    ports:
      - '5000:5000'
    links:
      - bokehapp
  bokehapp:
    build:
      context: .
      dockerfile: bokeh/Dockerfile
    volumes:
      - './bokeh:/app'
    ports:
      - '5006:5006'